apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustapi
  labels:
    app.kubernetes.io/name: rustapi
    app.kubernetes.io/instance: rustapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rustapi
      app.kubernetes.io/instance: rustapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rustapi
        app.kubernetes.io/instance: rustapi
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: rustapi
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          image: "dannylongeuay/ndsq-rustapi:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
          readinessProbe:
            httpGet:
              path: /ping
              port: http
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi