name: Find and Replace
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace Cargo
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'version = "\d+\.\d+\.\d+"'
          replace: 'version = "1.2.4"'
          include: "Cargo.toml"
      - name: Find and Replace Kustomization
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'newTag: \d+\.\d+\.\d+'
          replace: 'newTag: 1.2.4'
          include: "deploy/kustomization/kustomization.yaml"
      - name: Find and Replace Battlesnake
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'version: "\d+\.\d+\.\d+"'
          replace: 'version: "1.2.4"'
          include: "src/battlesnake.rs"
      - name: Add and Commit Changes
        uses: EndBug/add-and-commit@v9
