name: Release and Publish
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - "Cargo.toml"
jobs:
  get-tag:
    name: Get Tag Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.tag_step.outputs.new_tag}}
      version: ${{steps.tag_step.outputs.new_version}}
      log: ${{steps.tag_step.outputs.changelog}}
    steps:
      - uses: actions/checkout@v3
      - uses: mathieudutour/github-tag-action@v6.0
        id: tag_step
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
  update-and-tag:
    name: Update Files and Push Tag
    runs-on: ubuntu-latest
    needs: get-tag
    if: needs.get-tag.outputs.version != ''
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace Cargo
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '(?m)^version = "\d+\.\d+\.\d+"$'
          replace: 'version = "${{needs.get-tag.outputs.version}}"'
          include: "Cargo.toml"
      - name: Find and Replace Kustomization
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'newTag: \d+\.\d+\.\d+'
          replace: 'newTag: ${{needs.get-tag.outputs.version}}'
          include: "deploy/kustomization/kustomization.yaml"
      - name: Find and Replace Battlesnake
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: 'version: "\d+\.\d+\.\d+"'
          replace: 'version: "${{needs.get-tag.outputs.version}}"'
          include: "src/battlesnake.rs"
      - name: Add and Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          tag: ${{needs.get-tag.outputs.tag}}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [get-tag, update-and-tag]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{needs.get-tag.outputs.tag}}
          name: ndsq-rustapi - ${{needs.get-tag.outputs.version}}
          body: ${{needs.get-tag.outputs.log}}
  publish:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    needs: [get-tag, release]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dannylongeuay/ndsq-rustapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{needs.get-tag.outputs.version}}"